### ISSUE TITLE
Code Organisation 

### ISSUE THREAD

**Issue by Figeral** [BAM-Blockchain-African-Movement/ICP-Trashberry#1]
Hello dear Instructors , 
                                        Am current facing some challenges with my code  organisation . The project consist of a mobile a app , smart contract and a web app . since the dfx build tool automatically allow us to implement the backend and front end as web i was wandering were to place the source of my mobile app . 

+  should a create a  branch for the mobile app and another for the canister and web app ?  
+  or manage to put all that in the same  parent folder ?

**Comment by Emengkeng** [comment]
I think we will create a different repo for your mobile app.
